language: ruby
dist: bionic

addons:
  apt:
    packages:
      - rename

rvm:
  - 2.6.3

script: ./script/cibuild
after_success: ./script/cideploy

branches:
  only:
  - master

sudo: false

cache: bundler
