language: ruby
dist: bionic

rvm:
  - 2.6.3

script: ./script/cibuild
before_install: openssl aes-256-cbc -K $encrypted_641cbba37704_key -iv $encrypted_641cbba37704_iv -in deploy_key.enc -out deploy_key -d
after_success: ./script/cideploy

branches:
  only:
  - master

sudo: false

cache: bundler
