
exclude: [vendor, deploy_key.enc, TEMPLATE.shtml]

# Jekyll does not build hidden directories by default.
include: [".well-known"]

markdown_ext : "md,shtml"

highlighter: none

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

sass:
  style: compressed

plugins:
  - jekyll-redirect-from

