baseurl: ''
exclude: [vendor, deploy_key.enc, TEMPLATE.shtml, archive_html, dev_website]

# Google analytics
google_analytics: G-5FBPVMZYDF

# Jekyll does not build hidden directories by default.
include: [".well-known", ".htaccess"]

markdown_ext : "md,shtml"

highlighter: none

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

sass:
  style: compressed

plugins:
  - jekyll-redirect-from

