baseurl: ''
exclude: [vendor, deploy_key.enc, TEMPLATE.shtml, archive_html, dev_website]
key: chtc

#SEO
title: CHTC
tagline: Center for High Throughput Computing
description: UW-Madison team established to bring the power of High Throughput Computing to all fields of research.
url: https://chtc.cs.wisc.edu
twitter:
  username: chtc_uw
  card: summary

# Google analytics
google_analytics:

# Jekyll does not build hidden directories by default.
include:
  - ".well-known"
  - ".htaccess"
  - ".gitignore"
  - "icecube/.well-known"
  - "nsdf/.well-known"
  - "uwdf/researchdrive/.well-known"

exclude:
  - _events/images
  - _events/README.md
  - _presentations/images
  - _presentations/README.md

markdown_ext : "md,shtml"

highlighter: none

future: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "news"
    values:
      layout: news-page
      permalink: :title.html
  - scope:
      type: events_legacy
    values:
      layout: events
  - scope:
      type: events
    values:
      layout: events_modern
  - scope:
      type: redirects
    values:
      layout: redirect
  - scope:
      type: presentations
    values:
      layout: presentations


collections:
  news:
    permalink: /news/:path/
    output: true
  events_legacy:
    output: true
    permalink: /events/:year/:month/:title
  events:
    output: true
    permalink: /events/:year/:month/:day/:title
  redirects:
    output: true
  uw-research-computing:
    permalink: /uw-research-computing/:path
    output: true
  presentations:
    output: true
    permalink: /presentations/:year/:month/:day/:title

sass:
  style: compressed

plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag

