
exclude: [vendor, deploy_key.enc, TEMPLATE.shtml]

markdown_ex : "md,shtml"

highlighter: none

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-redirect-from

