baseurl: ''
exclude: [vendor, deploy_key.enc, TEMPLATE.shtml, archive_html, dev_website]
key: chtc

#SEO
title: CHTC
tagline: Center for High Throughput Computing
description: UW-Madison team established to bring the power of High Throughput Computing to all fields of research.
url: https://chtc.cs.wisc.edu
twitter:
  username: chtc_uw
  card: summary

# Google analytics
google_analytics:

# Jekyll does not build hidden directories by default.
include: [".well-known", ".htaccess", ".gitignore", "icecube/.well-known"]

markdown_ext : "md,shtml"

highlighter: none

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "news"
    values:
      layout: character_optimized
      permalink: :title.html
  - scope:
      type: events
    values:
      layout: events
  - scope:
      type: redirects
    values:
      layout: redirect


collections:
  news:
    permalink: /news/:path/
    output: true
  events:
    output: true
    permalink: /:collection/:year/:month/:title
  redirects:
    output: true

sass:
  style: compressed

plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag

