#!/bin/sh
set -e

if [ "$1" = "production" ]; then
  echo "Building Site For Production...";
  JEKYLL_ENV=production bundle exec jekyll build
else
  echo "Building Site For Development...";
  bundle exec jekyll build
fi;

