name: Build web pages
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_call:

permissions:
  actions: read

jobs:
  build-and-maybe-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          ref: master

      - name: Update Submodules
        run: git submodule update --init --recursive --remote

      - name: Attach hidden files
        run: |
          curl -H 'Authorization: token ${{ secrets.WEBSITE_STATS_TOKEN }}' \
          -H 'Accept: application/vnd.github.v3.raw' \
          -o assets/data/college-table.json \
          -f \
          -L https://api.github.com/repos/CHTC/website-stats/contents/college-table.json

          curl -H 'Authorization: token ${{ secrets.WEBSITE_STATS_TOKEN }}' \
          -H 'Accept: application/vnd.github.v3.raw' \
          -o assets/data/hero-stats.csv \
          -f \
          -L https://api.github.com/repos/CHTC/website-stats/contents/hero-stats.csv

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4
          bundler-cache: true

      - run: |
          ./script/cibuild production
        name: Build web pages

      - uses: CannonLock/search_index_build@master
        with:
          parameter_file_path: .search-bar.json
      # SSH key recipe from https://www.webfactory.de/blog/use-ssh-key-for-private-repositories-in-github-actions
      - name: Add the schedule file symlink
        run: |
          cd _site/staff
          ln -s /p/condor/public/html/developers/schedules schedules

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: chtc-website
          path: _site
          include-hidden-files: true
