name: Delete Web Previews
on:
  workflow_dispatch:
  delete:
    branches:
      - preview-**

jobs:
  delete-preview-page:
    if: ${{ github.repository_owner == 'CHTC' }}
    runs-on: ubuntu-latest
    env:
      preview_url: https://github.com/CHTC/web-preview.git

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Get branch name
        run: echo "BRANCH_NAME=${{ github.event.ref }}" >> $GITHUB_ENV

      - name: Setup SSH Keys and known_hosts
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.WEB_PREVIEW_DEPLOY_KEY }}

      - name: Build and Deploy
        run: |
          git remote add web-preview ${{ env.preview_url }}
          git fetch --all
          git checkout -b preview web-preview/main
          git rm -rf ${{ env.BRANCH_NAME }}
          git add .
          git commit -m "Remove the Deleted Branch"
          git push web-preview HEAD:main