name: Deploy web pages to Harbor

on:
  workflow_run:
    workflows: ["Build web pages"]
    types:
      - completed

jobs:

  check-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check for secrets
        run: |
          echo "Secrets: ${{ secrets }}"
    

  call-build-image:
    uses: osg-htc/build-push/.github/workflows/build-push.yaml@main
    secrets: inherit
    with:
      image: 'hub.opensciencegrid.org/chtc/chtc-website'
      artifact: chtc-website
