name: Check Links
on: [pull_request, workflow_dispatch]

jobs:
  Check-Website-Links:
    runs-on: ubuntu-latest

    steps:
      - uses: CHTC/test_links@master
        with:
          file_ignore: "/./staff/.*/,/./includes/.*/,/./doc/.*/"