
name: Deploy preview web area

on:
  push:
    branches: [preview]

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    if: startsWith(github.repository, 'CHTC/')
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true
      - run: |
          ./script/cibuild
        name: Build web pages
      # SSH key recipe from https://www.webfactory.de/blog/use-ssh-key-for-private-repositories-in-github-actions
      - run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-agent -a "$SSH_AUTH_SOCK" > /dev/null
          ssh-add - <<< "${{ secrets.PREVIEW_DEPLOY_KEY }}"
          ./script/cideploy
        env:
          #NO_PUSH: 1
          TARGET_REPO: CHTC/web-preview
          BRANCH: main
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        if: ${{ github.event_name != 'pull_request' && github.repository_owner == 'CHTC' }}
        name: Deploy preview web pages on merge/push
